### ISSUE TITLE
No menu on blog

### ISSUE THREAD

**Issue by softholyic** [ProgrammerMe/programmerme.github.io#21]
When a user clicks on blogs there's is no way of going back to home because there is no menu. I thought about fixing this but I wasn't sure whether to use the menu on index.html or the menu on blog/virtualsession.html. please let me if I should work on it and which menu to use.

**Comment by zameelpichen** [comment]
solved at commit [40d06fc4ba52f77da99f376516a3e2798ac274b8](https://github.com/ProgrammerMe/programmerme.github.io/commit/40d06fc4ba52f77da99f376516a3e2798ac274b8)
