### ISSUE TITLE
Proper Logo Needed

### ISSUE THREAD

**Issue by Siddharth1698** [ProgrammerMe/programmerme.github.io#26]
Design a proper logo for ProgrammerMe

**Comment by softholyic** [comment]
I'm no designer but I can spin off a few logos for you to choose from if you're keen @Siddharth1698

**Comment by Siddharth1698** [comment]
@softholyic Sure go ahead.

**Comment by hutriteguh** [comment]
![image](https://user-images.githubusercontent.com/46064613/52547786-8fdacb00-2dfc-11e9-81d3-5e88b4c7dda2.png)

wdyt? @Siddharth1698 @softholyic
